#!/bin/bash

set -e

usage() {
	cat >&2 <<-EOF
		usage: git fedora-github-archive <tag> [<name>]
	EOF
	return 1
}

[ $# -lt 1 -o $# -gt 2 ] && usage

tag="$1"
object_type="$(git cat-file -t "$tag")"

case "$object_type" in
	tag)
		object_hash="$(git cat-file tag "$tag" | awk '/^object / {print $2}')"
		;;
	commit)
		object_hash="$(git show "$tag" | awk '/^commit / {print $2}')"
		;;
	*)
		echo >&2 "fatal: not a tag: '$tag'"
		exit 1
		;;
esac

short_commit=${object_hash:0:7}

[ $# = 2 ] && name="$2" || name="$(basename "$PWD")"

git archive --format=tar.gz --prefix="$name-$object_hash/" "$object_hash" >"$name-$tag-$short_commit".tar.gz
