#!/bin/sh

set -e

usage() {
	cat >&2 <<-EOF
		usage: git cat <object>

		Have a break, have \`git cat\`!
	EOF
	return 1
}

[ $# != 1 ] && usage

object_type=$(git cat-file -t "$1")
git cat-file "$object_type" "$1"
