#!/bin/sh

set -e

get_last_modified() {
	# XXX this is not timezone-proof
	git log -100 --pretty=format:'%ci' -- "$1" |
	sort -r |
	head -1
}

print_last_modified() {
	printf "%s\t%s\n" "$(get_last_modified "$1")" "$1"
}

git ls-files -- "$@" |
while read -r file
do
	print_last_modified "$file"
done
