#!/bin/sh

set -e

SUBDIRECTORY_OK=yes
OPTIONS_KEEPDASHDASH=yes
OPTIONS_STUCKLONG=yes
OPTIONS_SPEC="\
git tree [-d]
--
 Available options are
d,directory-only!  list directories only
"
. git-sh-setup
require_work_tree_exists

match_type='blob|tree'

while test $# != 0
do
	case "$1" in
	--directory-only)
		match_type=tree
		;;
	--)
		shift
		break
		;;
	esac
	shift
done

[ $# -gt 0 ] && usage

tree_print() {
	printf '\n'
	printf '%s' "$1"
	printf ' %s' "$2"
	if [ "$3" = tree ]
	then
		tree "$4" "${1%???}|   |--"
	fi
}

tree_walk() {
	read -r mode type hash name || return 0

	while read -r mode next_type next_hash next_name
	do
		tree_print "$1" "$name" "$type" "$hash"
		type=$next_type
		hash=$next_hash
		name=$next_name
	done

	tree_print "${1%|--}'--" "$name" "$type" "$hash"
}

tree() {
	git ls-tree "$1" |
	awk '$2 ~ match_type' match_type="$match_type" |
	tree_walk "$2"
}

printf .
tree HEAD '|--'
printf '\n'
