#!/bin/sh

set -e
set -u

usage() {
	cat >&2 <<-EOF
	git-abort - Abort an ongoing operation

	usage: git abort

	Supported operations:

	- bisect
	- cherry-pick
	- merge
	- rebase
	- revert
	EOF
	return 1
}

test $# -gt 0 && usage

gitdir=$(git rev-parse --git-dir)

if [ -f "$gitdir/BISECT_LOG" ]
then
	git bisect reset
elif [ -f "$gitdir/CHERRY_PICK_HEAD" ]
then
	git cherry-pick --abort
elif [ -f "$gitdir/MERGE_HEAD" ]
then
	git merge --abort
elif [ -d "$gitdir/rebase-merge" ] || [ -d "$gitdir/rebase-apply" ]
then
	if [ -f "$gitdir/rebase-apply/rebasing" ]
	then
		git rebase --abort
	elif [ -f "$gitdir/rebase-apply/applying" ]
	then
		git am --abort
	else
		git am --abort || git rebase --abort
	fi
elif [ -f "$gitdir/REVERT_HEAD" ]
then
	git revert --abort
elif [ -f "$gitdir/sequencer/todo" ]
then
	read todo args <"$gitdir/sequencer/todo"
	case $todo in
	revert)
		git revert --abort
		;;
	p|pick)
		git cherry-pick --abort
		;;
	esac
else
	echo "git-abort: unsupported state, aborting." >&2
	exit 1
fi
